#!/bin/bash

retries="10"
action="lock"

while getopts "lur:" opt
do
  case $opt in
    l ) action="lock"		;;
    u ) action="unlock"		;;
    r ) retries="$OPTARG"	;;
    ? ) echo "$(basename $0): Unrecognize parameters"; exit 1	;;
  esac
done

shift $((OPTIND - 1))

#Output a multiline message to stdout
if [ $# -eq 0 ]
then
  cat << EOF >&2
Usage: $(basename $0) [-l][-u] [-r retries] LOCKFILE
Where -l requests a lock (the default), -u requests an unlock, -r X
specifies a max number of retries before it fails (default = $retries).
EOF
  exit 1
fi

#Ascertain if we have the lockfile command.

if [ -z "$(which lockfile | grep -v 'not found')" ]
then
  echo "$(basename $0) failed: 'lockfile' utility not found in PATH." >&2
  exit 1
fi

if [ "$action" = "lock" ]
then
  if ! lockfile -1 -r $retries "$1" 2> /dev/null
  then
    echo "$(basename $0): Failed: Couldn't create lockfile in time." >&2
    exit 1
  fi
else
  if [ ! -f "$1" ]
  then
    echo "$(basename $0): Warning: lockfile $1 doesn't exist to unlock." >&2
    exit 1
  fi
  rm -f "$1"
fi

exit 0