#!/bin/bash

. library.sh

echo "Hello $name"

echon "First off, do you have echo in your path? (1=yes 2=no): "
read answer

while ! validint $answer 1 2
do
  echon "Try again! Do you have echo "
  echon "in your path? (1=yes 2=no): "
  read answer
done

if ! checkForCmdInPath "echo"
then
  echo "Nope, can't find the echo command in the PATH"
else
  echo "The echo command is in the PATH."
fi

echo ""
echon "Enter a year you think might be a leap year: "
read year

while ! validint $year 1 9999
do
  echon "Please enter a year in the correct format!: "
  read year
done

if isLeapYear $year
then
  echo "You are right! $year is a leap year."
else
  echo "You are wrong"
fi

exit 0


