#!/bin/bash

archive_directory="$HOME/.deleted-files"
realrm="$(which rm)"
copy="$(which cp) -R"

if [ $# -eq 0 ]
then
  exec $realrm
fi

flags=""

while getopts "dfiPRrvW" opt
do
  case $opt in
    f ) exec $realrm "$@"      ;;
    * ) flags="$flags -$opt"   ;;
  esac
done

shift $(( $OPTIND - 1 ))

if [ ! -d "$archive_directory" ]
then
  if [ ! -w "$HOME" ]
  then
    echo "$(basename $0) failed - Can't create directory in $HOME" >&2
    exit 1
  fi
  mkdir "$archive_directory"
  chmod 700 "$archive_directory"
fi

for arg
do
  newname="$archive_directory/$(basename "$arg").$(date "+%S.%M.%H.%d.%m")"
  if [ -f "$arg" -o -d "$arg" ]
  then
    $copy "$arg" "$newname"
  fi
done

exec $realrm $flags "$@"
