#!/bin/bash

function nicenumber
{
  integer=$(echo $1 | cut -d. -f1)
  decimal=$(echo $1 | cut -d. -f2)

  if [ "$decimal" != $1 ]
  then
    result="${DD:='.'}$decimal"
  fi
  
  thousands=$integer

  while [ $thousands -gt 999 ]
  do
    remainder=$(($thousands%1000))
    
    while [ ${#remainder} -lt 3 ]
    do
      remainder="0${remainder}"
    done

    result="${TD:=","}${remainder}${result}"
    thousands=$(($thousands/1000))
  done

  nicenumber="$thousands$result"

  if [ ! -z $2 ]
  then
    echo $nicenumber
  fi
}

DD="."
TD=","

while getopts "d:t:" opt
do
  case $opt in
    d) DD="$OPTARG" ;; 
    t) TD="$OPTARG" ;;
  esac
done

shift $(($OPTIND - 1))

if [ $# -eq 0 ]
then
  echo "Usage: $(basename $0) [-d c] [-t c] number" >&2
  echo "-t for the thousands delimiter"
  echo "-d for the decimals delimiter"
  exit 1
fi

echo "Total to pay: \$$(nicenumber $1 1) USD"

exit 0
