#!/bin/bash

. validint

function  validFloat
{
	float="$1"
	if [ ! -z $(echo $float |  sed 's/[^.]//g' ) ]
	then
		decimal="$(echo $float | cut -d. -f1)"
		fractional="$(echo $float | cut -d. -f2)"
		
		if [ ! -z "$decimal" ]
		then
			if ! validint "$decimal" "" ""
			then
				return 1
			fi
		fi

		if [ ! -z "$fractional" ]
		then
			if [ $(echo $fractional | cut -c1) = "-" ]
			then
				return 1
			else
				if ! validint "$fractional" "" "" 
				then
					return 1
				fi
			fi
		else
			return 1
		fi
	else
		if [ "$float"	= "-" ]
		then
			return 1
		else
			if ! validint "$float" "" ""
			then
				return 1
			fi
		fi
	fi
	return 0
}

validFloat $1
