#!/bin/bash

function validAlphaNum
{
  validChars="$(echo $1 | sed -e 's/[^[:alnum:]]//g')"
  
  if [ "$validChars" = "$1" ]
  then
    return 0
  else
    return 1
  fi
}

#/bin/echo -n "provide a string: "
#read input

#if ! validAlphaNum "$input"
#then
#  echo "The string provided is not alphanumeric" >&2
#  exit 1
#else
#  echo "The string is valid" 
#fi

#exit 0
